blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/alexk1919/MackGPT/discussions/categories/q-a
    about: Ask questions and discuss with other community members
